name: Poll Github events every minute

on:
  schedule:
    - cron: '* * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: request to edge function

        run: |
          curl --request POST '$ {{ secrets.EDGE_FUNCTION_URL }}' \
          --header 'Authorization: ${{ secrets.SUPABASE_AUTH_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data '{ "ignore_old": true }'
